/// Every operational code the API can answer with, mapped onto the sentence
/// the reader actually needs.
///
/// The server writes its messages in English, for a developer reading a log.
/// Passing those through put `Business not found` on an Arabic screen whenever
/// a shop had closed. The code is the stable contract - the prose is not - so
/// the translation hangs off the code here, and several codes share one key
/// wherever the distinction would not change what the reader does next.
///
/// A code absent from this map still falls back to the server message, which
/// is the honest outcome: a code nobody has translated yet is a code nobody
/// has read.
library;

const Map<String, String> apiErrorMessageKeys = <String, String>{
  // -- Session and account -------------------------------------------------
  'AUTH_REQUIRED': 'apiErrors.authRequired',
  'AUTH_INVALID': 'apiErrors.sessionInvalid',
  'ACCOUNT_DISABLED': 'apiErrors.accountDisabled',
  'BUSINESS_ACCOUNT_DISABLED': 'apiErrors.businessAccountDisabled',
  'ACCOUNT_EXISTS': 'apiErrors.accountExists',
  'EMAIL_EXISTS': 'apiErrors.emailExists',
  'PHONE_EXISTS': 'apiErrors.phoneExists',
  'BUSINESS_IDENTIFIER_EXISTS': 'apiErrors.identifierExists',
  'INVALID_CREDENTIALS': 'apiErrors.invalidCredentials',
  'EMAIL_NOT_VERIFIED': 'apiErrors.emailNotVerified',
  'INVALID_VERIFICATION_TOKEN': 'apiErrors.invalidVerificationToken',
  'INVALID_PASSWORD_RESET_TOKEN': 'apiErrors.invalidResetToken',
  'PASSWORD_RECOVERY_RATE_LIMITED': 'apiErrors.passwordRateLimited',
  'LOGIN_RATE_LIMITED': 'apiErrors.loginRateLimited',
  'SIGNUP_RATE_LIMITED': 'apiErrors.signupRateLimited',
  'PASSWORD_RESET_RATE_LIMITED': 'apiErrors.passwordRateLimited',
  'INVALID_CURRENT_PASSWORD': 'apiErrors.invalidCurrentPassword',
  'INVALID_PASSWORD': 'apiErrors.invalidPassword',
  'INVALID_EMAIL': 'apiErrors.invalidEmail',
  'INVALID_PHONE': 'apiErrors.invalidPhone',
  'INVALID_NAME': 'apiErrors.invalidName',
  'INVALID_IDENTIFIER': 'apiErrors.invalidIdentifier',
  'NAME_CHANGE_LIMIT': 'apiErrors.nameChangeLimit',
  'GENDER_CHANGE_LIMIT': 'apiErrors.genderChangeLimit',
  'ACCOUNT_EMAIL_MISMATCH': 'apiErrors.accountEmailMismatch',
  'ACCOUNT_PHONE_MISMATCH': 'apiErrors.accountPhoneMismatch',
  'USER_NOT_FOUND': 'apiErrors.userNotFound',
  'INVALID_BIRTH_DATE': 'apiErrors.invalidBirthDate',
  'BUSINESS_ACCOUNT_REQUIRED': 'apiErrors.businessAccountRequired',
  'CUSTOMER_ACCOUNT_REQUIRED': 'apiErrors.customerAccountRequired',
  'BUSINESS_ALREADY_ENROLLED': 'apiErrors.businessAlreadyExists',
  'BUSINESS_ALREADY_EXISTS': 'apiErrors.businessAlreadyExists',

  // -- Addresses -----------------------------------------------------------
  'ADDRESS_NOT_FOUND': 'apiErrors.addressNotFound',
  'INVALID_ADDRESS_ID': 'apiErrors.addressNotFound',
  'ADDRESS_LIMIT_REACHED': 'apiErrors.addressLimitReached',
  'INVALID_ADDRESS_NAME': 'apiErrors.invalidAddressName',
  'INVALID_ADDRESS_PHONE': 'apiErrors.invalidAddressPhone',
  'INVALID_ADDRESS_CITY': 'apiErrors.invalidAddressCity',
  'INVALID_ADDRESS_GOVERNORATE': 'apiErrors.invalidAddressGovernorate',
  'INVALID_ADDRESS_DETAILS': 'apiErrors.invalidAddressDetails',
  'ADDRESS_GOVERNORATE_CLOSED': 'apiErrors.governorateClosed',

  // -- Business ------------------------------------------------------------
  'BUSINESS_NOT_FOUND': 'apiErrors.businessNotFound',
  'BUSINESS_PROFILE_NOT_FOUND': 'apiErrors.businessNotFound',
  'INVALID_BUSINESS_ID': 'apiErrors.businessNotFound',
  'INVALID_BUSINESS_NAME': 'apiErrors.invalidBusinessName',
  'INVALID_ENGLISH_NAME': 'apiErrors.invalidEnglishName',
  'INVALID_BUSINESS_CATEGORY': 'apiErrors.invalidBusinessCategory',
  'INVALID_BUSINESS_ADDRESS': 'apiErrors.invalidBusinessAddress',
  'INVALID_BUSINESS_DESCRIPTION': 'apiErrors.invalidBusinessDescription',
  'INVALID_BUSINESS_LOGO_URL': 'apiErrors.invalidBusinessUrl',
  'INVALID_ATTACHMENT_URL': 'apiErrors.invalidBusinessUrl',
  'INVALID_BUSINESS_SOCIAL_LINKS': 'apiErrors.invalidSocialLinks',
  'INVALID_BUSINESS_SOCIAL_NUMBER': 'apiErrors.invalidSocialLinks',

  // -- Products ------------------------------------------------------------
  'PRODUCT_NOT_FOUND': 'apiErrors.productNotFound',
  'INVALID_PRODUCT_ID': 'apiErrors.productNotFound',
  'INVALID_PRODUCT_NAME': 'apiErrors.invalidProductName',
  'INVALID_PRODUCT_PRICE': 'apiErrors.invalidProductPrice',
  'INVALID_PRODUCT_VARIANT_PRICE': 'apiErrors.invalidProductPrice',
  'INVALID_PRODUCT_COST_PRICE': 'apiErrors.invalidProductCostPrice',
  'INVALID_PRODUCT_VARIANT_COST_PRICE': 'apiErrors.invalidProductCostPrice',
  'INVALID_PRODUCT_DISCOUNT': 'apiErrors.invalidProductDiscount',
  'INVALID_PRODUCT_STOCK': 'apiErrors.invalidProductStock',
  'INVALID_PRODUCT_VARIANT_STOCK': 'apiErrors.invalidProductStock',
  'INVALID_PRODUCT_STOCK_MODE': 'apiErrors.invalidProductOption',
  'INVALID_PRODUCT_VARIANT_STOCK_MODE': 'apiErrors.invalidProductOption',
  'INVALID_PRODUCT_BOOLEAN': 'apiErrors.invalidProductOption',
  'INVALID_PRODUCT_VARIANT_BOOLEAN': 'apiErrors.invalidProductOption',
  'INVALID_PRODUCT_DESCRIPTION': 'apiErrors.invalidProductDescription',
  'INVALID_PRODUCT_KEYWORDS': 'apiErrors.invalidProductKeywords',
  'INVALID_PRODUCT_IMAGE_URL': 'apiErrors.invalidProductImage',
  'INVALID_PRODUCT_IMAGE_URLS': 'apiErrors.invalidProductImage',
  'INVALID_PRODUCT_VARIANT': 'apiErrors.invalidProductVariant',
  'INVALID_PRODUCT_VARIANTS': 'apiErrors.invalidProductVariant',
  'INVALID_PRODUCT_VARIANT_ID': 'apiErrors.invalidProductVariant',
  'INVALID_PRODUCT_VARIANT_LABEL': 'apiErrors.invalidProductVariant',
  'INVALID_PRODUCT_VARIANT_FIELDS': 'apiErrors.invalidProductVariant',
  'UNSUPPORTED_PRODUCT_VARIANT': 'apiErrors.invalidProductVariant',
  'INVALID_PRODUCT_CLASSIFICATION': 'apiErrors.invalidProductClassification',
  'INVALID_QUANTITY': 'apiErrors.invalidQuantity',

  // -- Orders --------------------------------------------------------------
  'ORDER_NOT_FOUND': 'apiErrors.orderNotFound',
  'INVALID_ORDER_ID': 'apiErrors.orderNotFound',
  'ORDER_NOT_CANCELLABLE': 'apiErrors.orderNotCancellable',
  'ORDER_ADDRESS_LOCKED': 'apiErrors.orderAddressLocked',
  'ORDER_COURIER_LOCKED': 'apiErrors.orderCourierLocked',
  'ORDER_NOTIFY_COOLDOWN': 'apiErrors.orderNotifyCooldown',
  'ORDER_STATUS_CONFLICT': 'apiErrors.orderStatusConflict',
  'INVALID_ORDER_STATUS_TRANSITION': 'apiErrors.invalidOrderStatusTransition',
  'INVALID_ORDER_STATUS': 'apiErrors.invalidOrderStatus',
  'INVALID_ORDER_STATUS_FIELDS': 'apiErrors.invalidOrderStatus',
  'INVALID_ORDER_STATUS_NOTE': 'apiErrors.invalidOrderStatusNote',
  'INVALID_ORDER_ITEMS': 'apiErrors.invalidOrderItems',
  'INVALID_ORDER_ITEM': 'apiErrors.invalidOrderItems',
  'DELIVERY_ADDRESS_REQUIRED': 'apiErrors.deliveryAddressRequired',
  'INVALID_DELIVERY_ADDRESS': 'apiErrors.invalidDeliveryAddress',
  'INVALID_ORDER_ADDRESS': 'apiErrors.invalidDeliveryAddress',
  'INVALID_DELIVERY_OPTION': 'apiErrors.invalidDeliveryOption',
  'INVALID_PAYMENT_METHOD': 'apiErrors.invalidPaymentMethod',
  'PAYMENT_METHOD_UNAVAILABLE': 'apiErrors.paymentMethodUnavailable',
  'INVALID_CANCELLATION_REASON': 'apiErrors.invalidCancellationReason',
  'INVALID_ORDER_COURIER_NAME': 'apiErrors.invalidCourierName',
  'INVALID_ORDER_COURIER_PHONE': 'apiErrors.invalidCourierPhone',
  'INVALID_ORDER_NUMBER': 'apiErrors.invalidOrderFilter',
  'INVALID_ORDER_SEARCH': 'apiErrors.invalidOrderFilter',
  'INVALID_ORDER_CUSTOMER': 'apiErrors.invalidOrderFilter',
  'INVALID_ORDER_DATE_FROM': 'apiErrors.invalidOrderFilter',
  'INVALID_ORDER_DATE_TO': 'apiErrors.invalidOrderFilter',
  'PRODUCT_OUT_OF_STOCK': 'apiErrors.productOutOfStock',

  // -- Checkout and inventory ----------------------------------------------
  'INSUFFICIENT_STOCK': 'apiErrors.insufficientStock',
  'PRODUCT_NOT_AVAILABLE': 'apiErrors.productUnavailable',
  'PRODUCT_VARIANT_REQUIRED': 'apiErrors.variantRequired',
  'PRODUCT_VARIANT_NOT_AVAILABLE': 'apiErrors.variantUnavailable',
  'PRODUCT_INVENTORY_RESERVED': 'apiErrors.inventoryReserved',
  'PRODUCT_INVENTORY_CHANGED': 'apiErrors.inventoryChanged',
  'CHECKOUT_IN_PROGRESS': 'apiErrors.checkoutInProgress',
  'CHECKOUT_CLAIM_LOST': 'apiErrors.checkoutClaimLost',
  'IDEMPOTENCY_KEY_REUSED': 'apiErrors.checkoutKeyReused',
  'COURIER_LOCATION_AUTH_REQUIRED': 'apiErrors.courierLocationAuthRequired',

  // -- Courier location ----------------------------------------------------
  'COURIER_LOCATION_CAPABILITY_INVALID': 'apiErrors.courierLocationInvalid',
  'COURIER_LOCATION_STALE_SAMPLE': 'apiErrors.courierLocationStale',
  'INVALID_COURIER_LOCATION_LATITUDE': 'apiErrors.invalidCourierLocation',
  'INVALID_COURIER_LOCATION_LONGITUDE': 'apiErrors.invalidCourierLocation',
  'INVALID_COURIER_LOCATION_ACCURACY': 'apiErrors.invalidCourierLocation',
  'INVALID_COURIER_LOCATION_CAPTURED_AT': 'apiErrors.invalidCourierLocation',
  'INVALID_COURIER_LOCATION_FIELDS': 'apiErrors.invalidCourierLocation',
  'CONVERSATION_NOT_FOUND': 'apiErrors.conversationNotFound',

  // -- Messages ------------------------------------------------------------
  'INVALID_CONVERSATION_ID': 'apiErrors.conversationNotFound',
  'INVALID_CONVERSATION_TARGET': 'apiErrors.invalidConversationTarget',
  'INVALID_MESSAGE_BODY': 'apiErrors.invalidMessageBody',
  'MESSAGE_STATE_INCONSISTENT': 'apiErrors.messageNotStored',
  'REVIEW_NOT_ELIGIBLE': 'apiErrors.reviewNotEligible',

  // -- Reviews, favourites and notifications -------------------------------
  'INVALID_RATING': 'apiErrors.invalidRating',
  'NOTIFICATION_NOT_FOUND': 'apiErrors.notificationNotFound',
  'INVALID_NOTIFICATION_ID': 'apiErrors.notificationNotFound',
  'INVALID_NOTIFICATION_PREFERENCE': 'apiErrors.invalidNotificationSetting',
  'INVALID_NOTIFICATION_AUDIENCE': 'apiErrors.invalidNotificationSetting',
  'INVALID_NOTIFICATION_FILTER': 'apiErrors.invalidNotificationSetting',
  'INVALID_PUSH_PLATFORM': 'apiErrors.invalidPushRegistration',
  'INVALID_PUSH_TARGET': 'apiErrors.invalidPushRegistration',
  'INVALID_PUSH_TARGET_KIND': 'apiErrors.invalidPushRegistration',
  'INVALID_PUSH_REGISTRATION_FIELDS': 'apiErrors.invalidPushRegistration',
  'RECOMMENDATION_CONSENT_REQUIRED': 'apiErrors.recommendationConsentRequired',
  'INVALID_PAGE': 'apiErrors.invalidPagination',

  // -- Search, paging and geography ----------------------------------------
  'INVALID_LIMIT': 'apiErrors.invalidPagination',
  'INVALID_BUSINESS_SEARCH': 'apiErrors.invalidSearch',
  'INVALID_BUSINESS_SORT': 'apiErrors.invalidSort',
  'INVALID_LATITUDE': 'apiErrors.invalidCoordinates',
  'INVALID_LONGITUDE': 'apiErrors.invalidCoordinates',
  'INCOMPLETE_NEARBY_COORDINATES': 'apiErrors.invalidCoordinates',
  'AMBIGUOUS_NEARBY_COORDINATES': 'apiErrors.invalidCoordinates',
  'INVALID_RADIUS_METERS': 'apiErrors.invalidRadius',
  'NOT_FOUND': 'apiErrors.routeNotFound',

  // -- Generic -------------------------------------------------------------
  'DUPLICATE_VALUE': 'apiErrors.duplicateValue',
  'INTERNAL_ERROR': 'apiErrors.unexpected',
  'VALIDATION_ERROR': 'apiErrors.invalidRequest',
  'INVALID_ID': 'apiErrors.invalidRequest',
  'INVALID_CLIENT_ORDER_ID': 'apiErrors.invalidRequest',
  'INVALID_FAVORITE_VALUE': 'apiErrors.invalidRequest',
  'INVALID_DISCOUNTED_FILTER': 'apiErrors.invalidRequest',
  'INVALID_CONVERSATION_FILTER': 'apiErrors.invalidRequest',
  'INVALID_BUSINESS_ENROLLMENT_FIELDS': 'apiErrors.invalidRequest',
  'INVALID_BUSINESS_PROFILE_FIELDS': 'apiErrors.invalidRequest',
  'INVALID_CANCELLATION_FIELDS': 'apiErrors.invalidRequest',
  'INVALID_CONVERSATION_FIELDS': 'apiErrors.invalidRequest',
  'INVALID_MESSAGE_FIELDS': 'apiErrors.invalidRequest',
  'INVALID_ORDER_ADDRESS_FIELDS': 'apiErrors.invalidRequest',
  'INVALID_ORDER_COURIER_FIELDS': 'apiErrors.invalidRequest',
  'INVALID_ORDER_FIELDS': 'apiErrors.invalidRequest',
  'INVALID_PASSWORD_RECOVERY_FIELDS': 'apiErrors.invalidRequest',
  'INVALID_PASSWORD_RESET_FIELDS': 'apiErrors.invalidRequest',
  'INVALID_PRODUCT_FIELDS': 'apiErrors.invalidRequest',
  'INVALID_PROFILE_FIELDS': 'apiErrors.invalidRequest',
  'INVALID_PROFILE_PERMISSIONS': 'apiErrors.invalidRequest',
  'INVALID_PROFILE_PERMISSION_FIELDS': 'apiErrors.invalidRequest',
  'INVALID_PROFILE_PERMISSION_VALUE': 'apiErrors.invalidRequest',
};
